name: expense_tracker
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  # Indentasi diperbaiki dan menggunakan rentang yang direkomendasikan
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # Semua dependensi di bawah ini diberi 2 spasi di depannya
  flutter:
    sdk: flutter
  
  fl_chart: ^0.68.0
  flutter_riverpod: ^2.5.1
  persistent_bottom_nav_bar_v2: ^6.1.0
  
  # Versi sqflite dan ffi disamakan untuk stabilitas
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3

  path: ^1.9.0
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^26.1.39 # Menggunakan versi terbaru
  
  # Versi intl diperbaiki ke versi yang valid
  intl: ^0.19.0 
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  # Diberi 2 spasi di depannya
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Menggunakan versi terbaru

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png